- name: varaiables from prompt
  hosts: local
  connection: local
  vars_prompts:
    - name: username
      prompt: What is your username?
      private: false
    - name: password
      prompt: What is your password?
      private: true
  tasks:
  - name: print credentials
    ansible.builtin.debug:
      msg: "Hello, Username is: {{ username }}, Password is: {{ password }}"
