- name: installing using loops
  hosts: local
  connection: local
  become: yes
  tasks:
   - name: print names
     ansible.builtin.package:
       name: "{{ item.name }}"
       state: "{{ item.status }}"
     loop:
      - { name: "nginx", state:"absent"}
      - { name: "mysql", state:"absent"} 
      - { name: "python", state:"present"}


